version: "3.9"

services:
  api:
    build:
      context: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/static
    restart: always
  db:
    build:
      context: backend/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/static
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

volumes:
  postgres_data:
  certbot_etc:
  certbot_var:
  static_volume: